"""add is_banned column to users

Revision ID: cc98806a37d9
Revises: 360fc126289d
Create Date: 2025-11-05 19:28:33.509081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc98806a37d9"
down_revision: Union[str, Sequence[str], None] = "360fc126289d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_banned", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_unique_constraint("uq_users_username", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_username", "users", type_="unique")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "is_banned")
    # ### end Alembic commands ###
