"""Add company_member table to connect users and their roles to companies

Revision ID: d2320cd60477
Revises: b590017da31f
Create Date: 2025-11-14 20:21:10.608313

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.utils.enum_utils import CompanyRole

# revision identifiers, used by Alembic.
revision: str = 'd2320cd60477'
down_revision: Union[str, Sequence[str], None] = 'b590017da31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_members',
                    sa.Column('company_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('role', sa.Integer(), nullable=False, server_default=str(CompanyRole.MEMBER.value)),
                    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('company_id', 'user_id')
                    )
    op.drop_table('company_admins')
    op.drop_constraint(op.f('companies_owner_id_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('companies_owner_id_fkey'), 'companies', 'users', ['owner_id'], ['id'],
                          ondelete='CASCADE')
    op.create_table('company_admins',
                    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'],
                                            name=op.f('company_admins_company_id_fkey'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('company_admins_user_id_fkey'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('company_id', 'user_id', name=op.f('company_admins_pkey'))
                    )
    op.drop_table('company_members')
    # ### end Alembic commands ###
