"""Add models to handle invitations and requests

Revision ID: eea8a8d2badf
Revises: d2320cd60477
Create Date: 2025-11-17 22:34:31.118915

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eea8a8d2badf'
down_revision: Union[str, Sequence[str], None] = 'd2320cd60477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_invitations',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('company_id', sa.UUID(), nullable=False),
                    sa.Column('invited_user_id', sa.UUID(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', name='messagestatus'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'invited_user_id')
                    )
    op.create_table('company_join_requests',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('company_id', sa.UUID(), nullable=False),
                    sa.Column('requesting_user_id', sa.UUID(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', name='messagestatus'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id', 'requesting_user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_join_requests')
    op.drop_table('company_invitations')
    op.execute("DROP TYPE messagestatus")
    # ### end Alembic commands ###
